name = "cjrcoding/cardano-color-changer"
version = "0.0.0"
compiler = "v1.1.7"
plutus = "v3"
license = "Apache-2.0"
description = "Aiken contracts for project 'cjrcoding/cardano-color-changer'"

[repository]
user = "cjrcoding"
project = "cardano-color-changer"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v2.2.0"
source = "github"

[config]
